# Generated by Django 4.0.4 on 2022-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
