# Generated by Django 4.0.4 on 2022-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0003_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
