# Generated by Django 4.0.4 on 2022-06-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0004_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения'),
        ),
    ]
