# Generated by Django 4.0.4 on 2022-06-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0005_alter_task_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50, verbose_name='Название папки')),
                ('parent_folder',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toDoListApp.folder',
                                   verbose_name='ID родительской папки')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toDoListApp.folder',
                                    verbose_name='ID папки'),
        ),
    ]
