# Generated by Django 4.0.4 on 2022-06-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0006_folder_task_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='folder_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='toDoListApp.folder', verbose_name='ID папки'),
        ),
    ]
