# Generated by Django 4.0.4 on 2022-06-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('toDoListApp', '0010_alter_folder_parent_folder_alter_task_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, default='folder_id', on_delete=django.db.models.deletion.CASCADE,
                                    to='toDoListApp.folder', verbose_name='ID родительской папки'),
        ),
    ]
